### ISSUE TITLE
Error:Error: getaddrinfo ENOTFOUND undefined undefined:443

### ISSUE THREAD

**Issue by SamirMatkar** [LivePersonInc/agent-sample-app#1]
Hello LivePerson

On following the steps from README.MD. after displaying the user name on console , on next line it's throwing below error message

Error:Error: getaddrinfo ENOTFOUND undefined undefined:443.

on looking into .js files, i found this "https://adminlogin.liveperson.net" is not reachable.

Any help to fix this would be appreciate.

Thanks in advance
Samir

**Comment by scottwestover** [comment]
Hi @SamirMatkar ,

The "https://adminlogin.liveperson.net" url is not meant to be reachable directly, but it is used to get the agentVep domain for the account you are trying to connect to (loginSession.js line 118)
`const url = ${config.lesession.csdsDomain}/csdr/account/${this.account}/service/agentVep/baseURI.json?version=1.0;`

I encountered the same error when I entered an incorrect account id. Can you please double check the account id that you used?

To verify if you visit - https://adminlogin.liveperson.net/csdr/account/{Your Account ID}/service/agentVep/baseURI.json?version=1.0 , (replace {Your Account ID}, with the account id you used), what is the response you get?

**Comment by LP-devsupport** [comment]
PR merged. Thanks @scottwestover
