### ISSUE TITLE
No click to start

### ISSUE THREAD

**Issue by motss** [LivePersonInc/agent-sample-app#4]
There is nothing to click to start chat.

**Comment by Premier** [comment]
Check console log

**Comment by motss** [comment]
That's not helpful! Thank you!

**Comment by donmanguno** [comment]
Hi @motss. If you still have a question please feel free to open a new issue, but please provide a more extensive description than "no click to start". Please explain what exactly you are trying to accomplish, what you are using, how you have set your environment up, what you are expecting to see, what you are seeing instead.
