### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by Premier** [LivePersonInc/agent-sample-app#5]
I've created an empty page and put your tag and started to chat. After a while the chat stops and a http error 403 appear into the browser console.
https://lptag.liveperson.net/tag/tag.js?site=60834595

Can you help me?

**Comment by donmanguno** [comment]
Hi @Premier 

This forum is reserved for code-related development questions. For general inquiries about how to add chat to your page please contact our support department via the Connection Panel on the right side of the LiveEngage UI

**Comment by donmanguno** [comment]
Hi @Premier 

Can you provide some more context for this inquiry? 

Is [the file you linked](https://lptag.liveperson.net/tag/tag.js?site=60834595) the tag you placed on your page?  [This document](https://ce-sr.s3.amazonaws.com/CA/Admin/LiveEngage%20Tag%20v2.2.pdf) explains how to properly tag your account.  Specifically, see see the section called **Option 1: Manual Implementation of the LiveEngage Tag** at the bottom of Page 3.

**Comment by Premier** [comment]
After a while, the button was appeared on my page and now i can use LivePerson. Thank you
